# Generated by Django 3.1.1 on 2020-09-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
